### ISSUE TITLE
Still some proprietary sprites?

### ISSUE THREAD

**Issue by alexgleason** [MaxMraz/oceans-heart-free-assets#3]
In [bush.png](https://raw.githubusercontent.com/MaxMraz/oceans-heart-free-assets/master/sprites/entities/bush.png) I recognize the Minish Cap bush on the right. Is this the only one?

Thank you!

**Comment by MaxMraz** [comment]
fuck! Thanks for catching that, Alex. I hadn't worked with any zelda graphics in so long I forgot minish cap's sprites actually looked like that. I thought that was me in my first, bad attempts to make a bush, hahahaha

**Comment by alexgleason** [comment]
Thank you!

**Comment by MaxMraz** [comment]
No, thank you ; )
